library(tidyverse)
library(openxlsx)
library(spatialreg)
library(sfdep)
library(tmap)
library(tmaptools)
library(zoo)
library(sp)
library(sf)
library(spdep)
library(GWmodel) 
library(spatialreg)
library(mgcv)
library(conflicted)
library(scales)
library(MASS)
library(classInt )
library(boot)
library(cowplot)
library(ggpubr)


conflict_prefer("select", "dplyr")
conflict_prefer("mutate", "dplyr")
conflict_prefer("recode", "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("rename", "dplyr")
conflict_prefer("summarize", "dplyr")
conflict_prefer("summarise", "dplyr")
conflict_prefer("arrange", "dplyr")
conflict_prefer("rbind.fill", "plyr")
conflict_prefer("group_by", "dplyr")


cbp1 <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#0072B2", "#D55E00", "#CC79A7")

col_c  <- c("#B078C0FF","#1EA7C4","#D36B8DFF")

col2 <- c("#B078C0FF","#56B4E9")